[package]
name = "certinfo-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.11", features = ["derive"] }
colored = "2.0.0"
hex-literal = "0.3.4"
x509-parser = "0.14.0"
